# Provide a custom message
message: "Msys Technologies Argo CD Demo tech talk_v_1.7"

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: NodePort
  port: 80

deployment:
  replicaCount: 3
  container:
    image:
      repository: "paulbouwer/hello-kubernetes"
      tag: 1.7
      pullPolicy: IfNotPresent
    port: 8080

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

